### ISSUE TITLE
Error starting Valhelsia 2 Server for the first time

### ISSUE THREAD

**Issue by hottubban** [Khytwel/Valhelsia#12]
`[21:07:40] [Server thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event LOAD_REGISTRIES, 1 errors found
[21:07:40] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Solar Flux Reborn (solarflux) encountered an error during the load_registries event phase
?7null
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189) ~[?:?] {re:classloading}
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:967) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:834) [?:?] {}
[21:07:40] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/mcserverlatest/serverfiles/./crash-reports/crash-2020-04-28_21.07.40-server.txt
`

**Comment by Vaelzan** [comment]
It's crashing because you're not using Java 8. This also isn't the place for support. Please use the Discord server for that:

https://discordapp.com/invite/reQZEXu
